//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace vtsadm {
    
    
    public partial class cs_rating_scale {
        
        protected global::System.Web.UI.WebControls.HiddenField hfId;
        
        protected global::System.Web.UI.WebControls.TextBox txtScaleName;
        
        protected global::System.Web.UI.WebControls.TextBox txtMin;
        
        protected global::System.Web.UI.WebControls.TextBox txtMax;
        
        protected global::System.Web.UI.WebControls.CheckBox chkActive;
        
        protected global::System.Web.UI.WebControls.Button btnSave;
        
        protected global::System.Web.UI.WebControls.Label lblMessage;
        
        protected global::System.Web.UI.WebControls.GridView gvData;
    }
}
