//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace vtsadm {
    
    
    public partial class cs_survey_category {
        
        protected global::System.Web.UI.WebControls.TextBox txtCategoryCode;
        
        protected global::System.Web.UI.WebControls.TextBox txtCategoryName;
        
        protected global::System.Web.UI.WebControls.TextBox txtDescription;
        
        protected global::System.Web.UI.WebControls.CheckBox chkIsActive;
        
        protected global::System.Web.UI.WebControls.HiddenField hfId;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl div_comment;
        
        protected global::System.Web.UI.WebControls.Button btnCancel;
        
        protected global::System.Web.UI.WebControls.Button btnSave;
        
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        
        protected global::System.Web.UI.HtmlControls.HtmlButton btnSearch;
        
        protected global::System.Web.UI.WebControls.GridView gvData;
        
        protected global::System.Web.UI.WebControls.Label LblPaging;
    }
}
