//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vtsadm
{
    public partial class expedition
    {
        protected global::System.Web.UI.WebControls.TextBox txtExpedisiID;
        protected global::System.Web.UI.WebControls.TextBox txtExpedisiName;
        protected global::System.Web.UI.WebControls.TextBox txtPICName;
        protected global::System.Web.UI.WebControls.TextBox txtPhone;
        protected global::System.Web.UI.WebControls.TextBox txtEmail;
        protected global::System.Web.UI.WebControls.TextBox txtAddress;
        protected global::System.Web.UI.HtmlControls.HtmlButton CmdClear;
        protected global::System.Web.UI.WebControls.Button CmdSubmit;
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.HtmlControls.HtmlButton CmdSearch;
        protected global::System.Web.UI.WebControls.GridView GridView1;
        protected global::System.Web.UI.WebControls.Label LblPaging;
        protected global::System.Web.UI.HtmlControls.HtmlButton CmdYesSubmit;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl LblExpedisiID;
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden txtExpedisiIDDelete;
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden txtStatusDelete;
        protected global::System.Web.UI.HtmlControls.HtmlButton CmdYesDelete;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl div_comment;
    }
}
