//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vtsadm
{
    public partial class mdvr_company_safety_ai_policy
    {
        protected global::System.Web.UI.WebControls.HiddenField hfIsEdit;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl div_comment;

        protected global::System.Web.UI.HtmlControls.HtmlInputText txtCompID;

        protected global::System.Web.UI.HtmlControls.HtmlButton BtnSearchCustomer;

        protected global::System.Web.UI.WebControls.TextBox txtCompanyName;

        protected global::System.Web.UI.HtmlControls.HtmlInputText txtIntervalSeconds;

        protected global::System.Web.UI.WebControls.CheckBox chkActive;

        protected global::System.Web.UI.WebControls.Button btnCancel;

        protected global::System.Web.UI.WebControls.Button btnSave;

        protected global::System.Web.UI.WebControls.GridView gvData;
    }
}
