//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------

namespace vtsadm
{
    public partial class mdvr_company_safety_ai_policy_company_search
    {
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtSearchCompany;

        protected global::System.Web.UI.HtmlControls.HtmlButton CmdSearchCust;

        protected global::System.Web.UI.WebControls.GridView GridView1;

        protected global::System.Web.UI.WebControls.Label LblPaging;
    }
}
