//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vtsadm
{
    public partial class setting_fuel_clbr
    {
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl div_comment;
        protected global::System.Web.UI.WebControls.HiddenField hidID;
        protected global::System.Web.UI.WebControls.DropDownList ddlVendor;
        protected global::System.Web.UI.WebControls.DropDownList ddlBrand;
        protected global::System.Web.UI.WebControls.DropDownList ddlType;
        protected global::System.Web.UI.WebControls.DropDownList ddlSensorType;
        protected global::System.Web.UI.WebControls.DropDownList ddlACC;
        protected global::System.Web.UI.WebControls.TextBox txtVoltage;
        protected global::System.Web.UI.WebControls.TextBox txtFuelValue;
        protected global::System.Web.UI.WebControls.Button btnSave;
        protected global::System.Web.UI.WebControls.Button btnReset;
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.LinkButton btnSearch;
        protected global::System.Web.UI.WebControls.GridView gvData;
        protected global::System.Web.UI.WebControls.Label lblPaging;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl div_message;
    }
}
